### ISSUE TITLE
怎么用VS 2017编译成静态库调用啊，编译很多错误

### ISSUE THREAD

**Issue by fengshangren** [JelinYao/HttpInterface#10]
我只想用WinHttp，想用VS2017编译成支持XP的MT静态库，给其它语言调用，请问怎么弄啊，下载了源码，直接编译都会有很多错误提示

**Comment by JelinYao** [comment]
发一下错误提示，改改就好了。

**Comment by fengshangren** [comment]
你有QQ吗或其它联系方式吗，能弄一个VS 2017静态库版本的吗

**Comment by fengshangren** [comment]
还有我看VS2010编译出来的DLL，函数只有三个，这个是不是不能用来其它语言调用的

**Comment by JelinYao** [comment]
可以用其他语言调用，但是只能在Windows上用。另外，我刚用VS2017编译没有报错呀，你是不是配置的不对。

**Comment by fengshangren** [comment]
ling61961980@qq.com 能发一份改成静态库的VS2017源码吗。我能直接编译成静态库调用那种，有头文件可以直接用的

**Comment by fengshangren** [comment]
谢谢，可以使用了，我封装的时候，发现POST提交功能并不完善，像Cookies的提交我没找到

**Comment by fengshangren** [comment]
还有下载的回调，不能类回调吗，我是封装到一个类里的，不能就在类里回调吗

**Comment by fengshangren** [comment]
还有 Request的参数都是多字节的吗，不支持宽字符吗

**Comment by fengshangren** [comment]
xp 访问http://www.baidu.com，返回不了任何东西

**Comment by fengshangren** [comment]
好像是只能访问有ssl的网站，没有ssl的都会返回失败

**Comment by fengshangren** [comment]
你是推荐用哪一种比较好，我现在就是封装的Winhttp.下载用着挺舒服的，我下载到本地，4G以上都能正常下载。还有就是POST这方面不是很细致.还有Request最后一个参数是协议头吗，格式是什么

**Comment by JelinYao** [comment]
推荐使用libcurl

**Comment by rkhorse** [comment]
请问，我编译成lib之后，但是测试的时候出现error LNK2001: 无法解析的外部符号 __imp__CreateInstance怎么解决呀
