### ISSUE TITLE
支持异步下载吗？

### ISSUE THREAD

**Issue by weituotian** [JelinYao/HttpInterface#12]
就是能够自动开线程下载，不阻塞界面

**Comment by JelinYao** [comment]
这个自己实现更方便，扩展性更好。

**Comment by weituotian** [comment]
@JelinYao 直接用std::thread吗？

**Comment by JelinYao** [comment]
可以用C++标准库的std::thread创建线程，也可以用Windows自己的API CreateThread创建线程，然后把HTTP请求放到线程里面去。
