### ISSUE TITLE
读取csdn.net的时候用cout输出不完整，应该是内容里有截断字符

### ISSUE THREAD

**Issue by ghost** [JelinYao/HttpInterface#4]
CWinHttp* pHttp = new CWinHttp();
	const wchar_t* pUrl = L"https://www.csdn.net";
	string strHtml = pHttp->Request(pUrl, HttpGet);
	if (strHtml.empty())
	{
		//请求失败
		pHttp->FreeInstance();
		return 0;
	}
	setlocale(LC_ALL, "");
	wstring outline = UTF8ToWstring(strHtml);
	printf_s("html : %.*ls", outline.size(), outline.c_str());

	pHttp->FreeInstance();
	return 0;

![图片](https://user-images.githubusercontent.com/10486636/82192034-fc107c80-9925-11ea-9361-f959271c22a0.png)

![图片](https://user-images.githubusercontent.com/10486636/82192070-0b8fc580-9926-11ea-81ea-5a4507414280.png)

**Comment by ghost** [comment]
试了 printf_s  printf wprintf cout wcout 输出，结果都一样，输出不完整，输出 https://www.qq.com  163.com这些都正常。 调试了一下，没找到原因，把 html用 .data()函数转成数组，再遍历，没有发现内容中间有'\0'

html的值转换成wstring, 在VS 2019的debug里查看，能得到完整的内容。

**Comment by JelinYao** [comment]
![image](https://user-images.githubusercontent.com/7205249/82213187-54f00d00-9946-11ea-886a-7a9f1286be70.png)
我测试了一下，正常输出的，你看下是不是你的转码函数有问题。另外，截图代码明显有误：不要用printf_s打印unicode字符串。
