### ISSUE TITLE
winhttp.h 有啥用？

### ISSUE THREAD

**Issue by sgf** [JelinYao/HttpInterface#5]
Win10 VS2019 上面 我去掉了之后似乎也可以正常编译IHttp 和UseHttp 两个项目啊？

**Comment by JelinYao** [comment]
![image](https://user-images.githubusercontent.com/7205249/82444255-8814d680-9ad5-11ea-93ff-8e405bcca87f.png)

早期的Windows SDK里面有很多HTTP宏没有定义，在低版本的VS上（VS2008、2010）会报错，需要带上。高版本的VS我没试过，不需要就可以删掉。

**Comment by sgf** [comment]
原来如此 感谢回复。
