### ISSUE TITLE
大神你好，下载的时候返回12152是什么原因啊

### ISSUE THREAD

**Issue by cagedh1** [JelinYao/HttpInterface#7]

**Comment by JelinYao** [comment]
winhttp.h中有定义这个错误
#define WINHTTP_ERROR_BASE                     12000
#define ERROR_WINHTTP_INVALID_SERVER_RESPONSE      (WINHTTP_ERROR_BASE + 152)
原因：The server response could not be parsed
可以调试看下返回结果是否是http格式的。

**Comment by cagedh1** [comment]
> winhttp.h中有定义这个错误
> #define WINHTTP_ERROR_BASE 12000
> #define ERROR_WINHTTP_INVALID_SERVER_RESPONSE (WINHTTP_ERROR_BASE + 152)
> 原因：The server response could not be parsed
> 可以调试看下返回结果是否是http格式的。

谢谢大神，回复，我用您的程序将执行文件下载到内存好像不太成功。。

**Comment by JelinYao** [comment]
不用客气。可以帖下你调用的代码，我看看是哪里有问题。

**Comment by cagedh1** [comment]
> 不用客气。可以帖下你调用的代码，我看看是哪里有问题。

我测试，可能应该是网络问题，大神方便的话能留个联系方式吗

**Comment by JelinYao** [comment]
QQ不常在：307396091。
