### ISSUE TITLE
怎么使用httppost

### ISSUE THREAD

**Issue by Ives88** [JelinYao/HttpInterface#8]
我是c++小白，之前做java的，示例里只有get的，能不能提供一个post的使用？body参数和header要怎么传？可以是{"name":"myname"}这种json格式作为参数传进去吗？谢谢了

**Comment by JelinYao** [comment]
代码已更新，支持添加http请求头，添加post测试代码。

**Comment by Ives88** [comment]
最新代码取下来，找不到httpHeader这个类和头文件

**Comment by JelinYao** [comment]
sorry，昨天新加的两个文件忘了提交，已更新。

**Comment by Ives88** [comment]
好的，解决问题了！谢谢楼主
